### ISSUE TITLE
search problem

### ISSUE THREAD

**Issue by talgautb** [himynameisdave/postcss-plugins#10]
![screenshot from 2015-09-17 09 36 52](https://cloud.githubusercontent.com/assets/1547797/9924290/ccfaab2e-5d1f-11e5-861b-5ffd35129b2c.png)

is it ok?!)

**Comment by himynameisdave** [comment]
Yeah so @mxstbr, the guy who runs [postcss.parts](http://postcss.parts), has not updated the version of this plugin list that it uses in some time.

We are working together on a solution that always displays the most up-to-date info, but until then maybe [file an issue over in that repo](https://github.com/mxstbr/postcss.parts/issues/new) because it is currently just using [a really old version](https://github.com/mxstbr/postcss.parts/blob/master/package.json#L8) of the plugin list.

**Comment by mxstbr** [comment]
Done, sorry about the delay. Plugins are now loaded client side, so they are always up to date. See here for more info: https://github.com/mxstbr/postcss.parts/commit/54741a7bdbd6e31e199366a9957f883ea98653b3
