### ISSUE TITLE
To update plugin or add again?

### ISSUE THREAD

**Issue by peterramsing** [himynameisdave/postcss-plugins#57]
I'm the new maintainer of the Lost Grid–thus it has a new url. Should I submit a new plugin or is there a way to update existing plugins?

Thanks!

**Comment by himynameisdave** [comment]
Hey! Sorry for the late response! You should update the existing one instead of adding another!

***Steps:***
1. fork the repo
2. edit [these lines](https://github.com/himynameisdave/postcss-plugins/blob/master/plugins.json#L881-L889)
3. Commit, push, and then [open a pull request](https://github.com/himynameisdave/postcss-plugins/compare)

**Comment by peterramsing** [comment]
Thanks!
